# Generated by Django 5.2 on 2025-05-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postitem_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='blur_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postitem',
            name='time_found',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
