# Generated by Django 5.1.6 on 2025-03-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundit', '0002_lostitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
