# Generated by Django 5.1.6 on 2025-03-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundit', '0003_remove_user_phone_number_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='aziz', max_length=20),
            preserve_default=False,
        ),
    ]
